### ISSUE TITLE
npm run bundle-js not working for chat-template@0.0.26 

### ISSUE THREAD

**Issue by rajgupt** [sevenleaps/chat-template#19]
Chat-Template version - 0.0.26
React version - 15.1.0
Browser version - chrome 64.X

```
$ npm run bundle-js

> chat-template@0.0.26 bundle-js C:\Users\rajat\projects\knowledge\git\duplicate\chat-template
> npm run test && npm run bundle-js-dev && npm run bundle-js-prod


> chat-template@0.0.26 test C:\Users\rajat\projects\knowledge\git\duplicate\chat-template
> npm run lint && npm run testonly


> chat-template@0.0.26 lint C:\Users\rajat\projects\knowledge\git\duplicate\chat-template
> eslint src


> chat-template@0.0.26 testonly C:\Users\rajat\projects\knowledge\git\duplicate\chat-template
> mocha --require .scripts/mocha_runner src/**/tests/**/*.js



  <Avatar /> shallow
    √ renders an Avatar element with one message

  <Avatar /> mount
    √ renders an Avatar element with one message (41ms)

  <Conversation /> shallow
    √ renders a Messages element with no messages
Warning: Failed propType: Required prop `messages[0].inbound` was not specified in `Conversation`.
    √ renders one Messages element with one message

  <Conversation /> mount
Warning: render(): Rendering components directly into document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try rendering into a container element created for your app.
    √ renders a Messages element with no messages
Warning: render(): Rendering components directly into document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try rendering into a container element created for your app.
    √ renders one Messages element with one message

  <ImageLoader /> shallow
    √ renders a ImageLoader element with no images
    √ renders one ImageLoader element with one image

  <Message /> shallow
    √ renders a Message element with one message
    √ renders a Message element with one message with an Avatar

  <MessageContent /> shallow
Warning: Failed propType: Required prop `message.inbound` was not specified in `MessageContent`.
    √ renders a MessageContent element with no messages
    √ renders one MessageContent element with one message

  <Messages /> shallow
    √ renders a Messages element with no messages
    √ renders one Messages element with one message

  <Typing /> shalllow
    √ renders Typing to have 4 divs


  15 passing (271ms)


> chat-template@0.0.26 bundle-js-dev C:\Users\rajat\projects\knowledge\git\duplicate\chat-template
> webpack --config ./webpack.dev.config.js

Hash: 182b32d2f531fa8b2036
Version: webpack 1.13.1
Time: 41ms
   [0] ./src/bundle/wrapper.js 0 bytes [built] [failed]

ERROR in ./src/bundle/wrapper.js
Module parse failed: C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\src\bundle\wrapper.js Unexpected token (6:18)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (6:18)
    at Parser.pp$4.raise (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExprList (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExpression (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1573:21)
    at Parser.pp$1.parseStatement (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:727:47)
    at Parser.pp$1.parseBlock (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:2105:24)
    at Parser.pp$3.parseArrowExpression (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:2087:10)
    at Parser.pp$3.parseParenArrowList (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1902:17)
    at Parser.pp$3.parseParenAndDistinguishExpression (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1870:21)
    at Parser.pp$3.parseExprAtom (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1796:19)
    at Parser.pp$3.parseExprSubscripts (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$1.parseVar (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1034:28)
    at Parser.pp$1.parseVarStatement (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:917:10)

> chat-template@0.0.26 bundle-js-prod C:\Users\rajat\projects\knowledge\git\duplicate\chat-template
> webpack -p --config ./webpack.prod.config.js

Hash: a604358a5c60be13ae79
Version: webpack 1.13.1
Time: 53ms
   [0] ./src/bundle/wrapper.js 0 bytes [built] [failed]

ERROR in ./src/bundle/wrapper.js
Module parse failed: C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\src\bundle\wrapper.js Unexpected token (6:18)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (6:18)
    at Parser.pp$4.raise (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExprList (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExpression (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1573:21)
    at Parser.pp$1.parseStatement (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:727:47)
    at Parser.pp$1.parseBlock (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:2105:24)
    at Parser.pp$3.parseArrowExpression (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:2087:10)
    at Parser.pp$3.parseParenArrowList (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1902:17)
    at Parser.pp$3.parseParenAndDistinguishExpression (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1870:21)
    at Parser.pp$3.parseExprAtom (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1796:19)
    at Parser.pp$3.parseExprSubscripts (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$1.parseVar (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:1034:28)
    at Parser.pp$1.parseVarStatement (C:\Users\rajat\projects\knowledge\git\duplicate\chat-template\node_modules\acorn\dist\acorn.js:917:10)

```

**Comment by paulofla** [comment]
Hi @rajgupt 

Thanks for opening an issue!

Is this issue still affecting you? I see that you opened and closed a pull request.

Thanks,
Paul

**Comment by paulofla** [comment]
Hi @rajgupt 

I tried a fresh install and this works for me.

If you try with a fresh install and this still occurs, I'd be interested to see what is in your package-lock.json file or shrinkwrap file and what version of node and npm you are using.

Also I appreciate the update in the webpack version in your pull request. (This project hasn't gotten much attention in a while!) I don't want to merge your change until we can figure out the root cause of the issue you got above.

Thanks,
Paul

**Comment by rajgupt** [comment]
I believe it should be fixed as it is working for you. Unfortunately, unable to test it currently hence closing for now.
Thanks
Rajat
